#
#           ██╗  ██╗ █████╗  ██████╗██╗  ██╗███████╗██████╗  ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗ ██╗ █████╗ ███╗   ██╗
#           ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗████╗  ██║
#           ███████║███████║██║     █████╔╝ █████╗  ██████╔╝██║  ███╗██║   ██║███████║██████╔╝██║  ██║██║███████║██╔██╗ ██║
#           ██╔══██║██╔══██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║██║██╔══██║██║╚██╗██║
#           ██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║  ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝██║██║  ██║██║ ╚████║
#           ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝

SQLHost: '127.0.0.1' #This should be the ip to your database
SQLPort: '3306' #This should be the port to your database.
SQLDatabaseName: 'myDatabase' #This should be the database name to your database.
SQLUsername: 'changeme' #This should be the database username to your database
SQLPassword: 'changeme' #This should be the database password to your database
debug: false #Enable if I ask you to.
#General settings
Settings:
  UseWebsiteFunction: false #Should HackerGuardian use HackerGuardian-Webserver if it's present and connectable? (not in this build)
  EnableAI: false #Want to use the AI part of the Anti-Cheat (ALPHA)
  LearningMode: false #Should the AI be in Learning mode? (ALPHA) (not in this build)
  UseDBForAIData: false #Should we store the learned data in the database instead of the local machine? (not ready for use)

#Webserver settings
SettingsWeb:
  webdomain: your-domain.net
  webapikey: your-api-key-here
