SQLHost: '127.0.0.1' #This should be the ip to your database
SQLPort: '3306' #This should be the port to your database.
SQLDatabaseName: 'myDatabase' #This should be the database name to your database.
SQLUsername: 'changeme' #This should be the database username to your database
SQLPassword: 'changeme' #This should be the database password to your database
debug: false #Enable if I ask you to.