#
#           ██╗  ██╗ █████╗  ██████╗██╗  ██╗███████╗██████╗  ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗ ██╗ █████╗ ███╗   ██╗
#           ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██╔════╝██╔══██╗██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗██║██╔══██╗████╗  ██║
#           ███████║███████║██║     █████╔╝ █████╗  ██████╔╝██║  ███╗██║   ██║███████║██████╔╝██║  ██║██║███████║██╔██╗ ██║
#           ██╔══██║██╔══██║██║     ██╔═██╗ ██╔══╝  ██╔══██╗██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║██║██╔══██║██║╚██╗██║
#           ██║  ██║██║  ██║╚██████╗██║  ██╗███████╗██║  ██║╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝██║██║  ██║██║ ╚████║
#           ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝
#          █████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗█████╗
#          ╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝
#                         ██╗███╗   ███╗██████╗  ██████╗ ██████╗ ████████╗ █████╗ ███╗   ██╗████████╗██╗
#                         ██║████╗ ████║██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔══██╗████╗  ██║╚══██╔══╝██║
#                         ██║██╔████╔██║██████╔╝██║   ██║██████╔╝   ██║   ███████║██╔██╗ ██║   ██║   ██║
#                         ██║██║╚██╔╝██║██╔═══╝ ██║   ██║██╔══██╗   ██║   ██╔══██║██║╚██╗██║   ██║   ╚═╝
#                         ██║██║ ╚═╝ ██║██║     ╚██████╔╝██║  ██║   ██║   ██║  ██║██║ ╚████║   ██║   ██╗
#                         ╚═╝╚═╝     ╚═╝╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝

#So little heads up before you make a connection to your database. IF you are planning to use my addon: HackerGuardian-Webserver
#I highly recommend to use the same database as the websystem and hackerguardian mostly communicate through the database.
SQLHost: '127.0.0.1' #This should be the ip to your database
SQLPort: '3306' #This should be the port to your database
SQLDatabaseName: 'myDatabase' #This should be the database name to your database.
SQLUsername: 'changeme' #This shuld be the database username to your database
SQLPassword: 'changeme' #This shuld be the database password to your database
debug: false #Enable if I ask you to.
#General stuff
Settings:
  CheckWebsiteFunction: false #Should HackerGuardian check if HackerGuardian-Webserver is present in the database?
  autoaddtobanwave: false #Should HackerGuardian add the player to banwave after it found the player guilty of cheats?
  logplayerip: false #Should HackerGuardian add the players IP to a list?
  ReportViewTime: 48 #Max staff reports view time (in hours).
  MaxIPListCount: 3 #Max ip count on in-game log.
  MaxModsListCount: 5 #Max mods count on in-game log. (only applies of user used forge)
  MaxReasonListCount: 5 #Max Checks Trigger counts on in-game log.
  MaxHandlerListCount: 5 #Max handler list count on in-game log.
  Addoneachtriggercoung: false #Should HackerGuardian add the suspicion each time its triggered or only on kick? True is yes, False is no
  mintps: 14 #Counter measures will be used if tps gets bellow this.
  maxtps: 19 #Counter measures will be stopped if tps is equal or greater than this.
  AutoUpdate: true #Should HackerGuardian AutoUpdate when an update is available?

#Webserver settings
webdomain: your-domain.net
webapikey: your-api-key-here
