SQLHost: '127.0.0.1' #This should be the ip to your database
SQLPort: '3306' #This should be the port to your database.
SQLDatabaseName: 'myDatabase' #This should be the database name to your database.
SQLUsername: 'changeme' #This should be the database username to your database
SQLPassword: 'changeme' #This should be the database password to your database
debug: false #Enable if I ask you to.

Settings:
  shared_secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
  verify_window_ms: 2000
  hg_secure_link: false #HackerGuardian secure link system to prevent none authorized proxies and direct connection.
  behind_proxy: true #Often true for API access for the webaddon
  UseWebsiteFunction: false # true if you use webaddon

SettingsWeb:
  Api:
    enabled: true
    bind_host: "0.0.0.0"
    bind_port: 8787
    require_auth: true
    allowed_skew_ms: 90000
    nonce_ttl_ms: 300000

    keys:
      panel-1: "CHANGE_ME_TO_LONG_RANDOM_SECRET"


#Moderation settings
Punishments:
  #Usable inputs %expires% %reason% %id%
  messages:
    kick: "&cYou were kicked.\n&7Reason: &f%reason%"
    ban_kick: "&cYou are banned.\n&7Reason: &f%reason%"
    ban_join: "&cYou are banned.\n&7Reason: &f%reason%\n&7Expires: &f%expires%"
    ipban_join: "&cThe ip you are joining from is banned.\n&7Reason: &f%reason%"
    ipban_kick: "&cYou are IP-banned.\n&7Reason: &f%reason%"

    ban_join_temp: |
      &cYou are temporarily banned for &f%expires% &cfrom this server!

      &7Reason: &f%reason%
      &7Find out more: &bhttps://your.site/appeal

      &7Ban ID: &f#%id%
      &7Sharing your Ban ID may affect the processing of your appeal!

    ban_join_perm: |
      &cYou are permanently banned from this server!

      &7Reason: &f%reason%
      &7Find out more: &bhttps://your.site/appeal

      &7Ban ID: &f#%id%
      &7Sharing your Ban ID may affect the processing of your appeal!

    muted_chat: |
      &cYou are muted.

      &7Reason: &f%reason%
      &7Expires in: &f%expires%

    ipban_join_temp: |
      &cYou are temporarily IP-banned for &f%expires% &cfrom this server!

      &7Reason: &f%reason%
      &7Find out more: &bhttps://your.site/appeal

      &7IP Ban ID: &f#%id%
      &7Sharing your Ban ID may affect the processing of your appeal!

    ipban_join_perm: |
      &cYou are permanently IP-banned from this server!

      &7Reason: &f%reason%
      &7Find out more: &bhttps://your.site/appeal

      &7IP Ban ID: &f#%id%
      &7Sharing your Ban ID may affect the processing of your appeal!