name: HackerGuardian
main: me.hackerguardian.main.HackerGuardian
version: 2
description: HackerGuardian, an anti-cheat with versatile cheat detection.
author: HypersMC
libraries:
  - com.caucho:quercus:4.0.44
  - org.apache.commons:commons-lang3:3.12.0
  - org.apache.commons:commons-text:1.10.0
  - org.apache.commons:commons-configuration2:2.8.0
  - commons-validator:commons-validator:1.7
  - io.netty:netty-buffer:4.1.85.Final
  - com.github.neuroph:neuroph-core:2.98
api-version: 1.13
softdepend: [ProtocolLib, ViaVersion, ProtocolSupport]
database: true
load: POSTWORLD
folia-supported: false
commands:
  HackerGuardian: